# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('unit', models.CharField(max_length=10)),
                ('amount', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
        migrations.RemoveField(
            model_name='recipestep',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='recipestep',
            name='name',
        ),
        migrations.AddField(
            model_name='recipestep',
            name='instructions',
            field=models.CharField(blank=True, default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='recipestep',
            name='ingredients',
            field=models.ManyToManyField(to='recipe.IngredientValue'),
        ),
    ]
