# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 22:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_auto_20170503_1138'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IngredientValue',
            new_name='Ingredient',
        ),
    ]
